## Data cleaning and preprocessing ##

In [1]:
import pandas as pd

In [2]:
houses = pd.read_csv('train.csv')
houses.head(5)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

Let's drop the Id column since it doesn't give important information.

In [3]:
houses = houses.drop(labels='Id', axis=1)
houses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 80 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   MSZoning       1460 non-null   object
 2   LotFrontage    1201 non-null   float64
 3   LotArea        1460 non-null   int64
 4   Street         1460 non-null   object
 5   Alley          91 non-null     object
 6   LotShape       1460 non-null   object
 7   LandContour    1460 non-null   object
 8   Utilities      1460 non-null   object
 9   LotConfig      1460 non-null   object
 10  LandSlope      1460 non-null   object
 11  Neighborhood   1460 non-null   object
 12  Condition1     1460 non-null   object
 13  Condition2     1460 non-null   object
 14  BldgType       1460 non-null   object
 15  HouseStyle     1460 non-null   object
 16  OverallQual    1460 non-null   int64
 17  OverallCond    1460 non-null   int64
 18  YearBuilt      1460 non-null   int64
 19  YearRemodAdd   1460 non-null   int64
 20  RoofStyle      1460 non-null   object
 21  RoofMatl       1460 non-null   object
 22  Exterior1st    1460 non-null   object
 23  Exterior2nd    1460 non-null   object
 24  MasVnrType     588 non-null    object
 25  MasVnrArea     1452 non-null   float64
 26  ExterQual      1460 non-null   object
 27  ExterCond      1460 non-null   object
 28  Foundation     1460 non-null   object
 29  BsmtQual       1423 non-null   object
 30  BsmtCond       1423 non-null   object
 31  BsmtExposure   1422 non-null   object
 32  BsmtFinType1   1423 non-null   object
 33  BsmtFinSF1     1460 non-null   int64
 34  BsmtFinType2   1422 non-null   object
 35  BsmtFinSF2     1460 non-null   int64
 36  BsmtUnfSF      1460 non-null   int64
 37  TotalBsmtSF    1460 non-null   int64
 38  Heating        1460 non-null   object
 39  HeatingQC      1460 non-null   object
 40  CentralAir     1460 non-null   object
 41  Electrical     1459 non-null   object
 42  1stFlrSF       1460 non-null   int64
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   object
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   object
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    770 non-null    object
 57  GarageType     1379 non-null   object
 58  GarageYrBlt    1379 non-null   float64
 59  GarageFinish   1379 non-null   object
 60  GarageCars     1460 non-null   int64
 61  GarageArea     1460 non-null   int64
 62  GarageQual     1379 non-null   object
 63  GarageCond     1379 non-null   object
 64  PavedDrive     1460 non-null   object
 65  WoodDeckSF     1460 non-null   int64
 66  OpenPorchSF    1460 non-null   int64
 67  EnclosedPorch  1460 non-null   int64
 68  3SsnPorch      1460 non-null   int64
 69  ScreenPorch    1460 non-null   int64
 70  PoolArea       1460 non-null   int64
 71  PoolQC         7 non-null      object
 72  Fence          281 non-null    object
 73  MiscFeature    54 non-null     object
 74  MiscVal        1460 non-null   int64
 75  MoSold         1460 non-null   int64
 76  YrSold         1460 non-null   int64
 77  SaleType       1460 non-null   object
 78  SaleCondition  1460 non-null   object
 79  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34), object(43)
memory usage: 912.6+ KB

In [146]:
houses.describe()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,46.549315,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,161.319273,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,0.000000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,0.000000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,1474.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [4]:
#Separate columns into numerical data and categorical data

houses_numerical_cols = houses.select_dtypes(include='number')

houses_categorical_cols = houses.select_dtypes(exclude='number')

In [148]:
houses_categorical_cols.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 43 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSZoning       1460 non-null   object
 1   Street         1460 non-null   object
 2   Alley          91 non-null     object
 3   LotShape       1460 non-null   object
 4   LandContour    1460 non-null   object
 5   Utilities      1460 non-null   object
 6   LotConfig      1460 non-null   object
 7   LandSlope      1460 non-null   object
 8   Neighborhood   1460 non-null   object
 9   Condition1     1460 non-null   object
 10  Condition2     1460 non-null   object
 11  BldgType       1460 non-null   object
 12  HouseStyle     1460 non-null   object
 13  RoofStyle      1460 non-null   object
 14  RoofMatl       1460 non-null   object
 15  Exterior1st    1460 non-null   object
 16  Exterior2nd    1460 non-null   object
 17  MasVnrType     588 non-null    object
 18  ExterQual      1460 non-null   object
 19  ExterCond      1460 non-null   object
 20  Foundation     1460 non-null   object
 21  BsmtQual       1423 non-null   object
 22  BsmtCond       1423 non-null   object
 23  BsmtExposure   1422 non-null   object
 24  BsmtFinType1   1423 non-null   object
 25  BsmtFinType2   1422 non-null   object
 26  Heating        1460 non-null   object
 27  HeatingQC      1460 non-null   object
 28  CentralAir     1460 non-null   object
 29  Electrical     1459 non-null   object
 30  KitchenQual    1460 non-null   object
 31  Functional     1460 non-null   object
 32  FireplaceQu    770 non-null    object
 33  GarageType     1379 non-null   object
 34  GarageFinish   1379 non-null   object
 35  GarageQual     1379 non-null   object
 36  GarageCond     1379 non-null   object
 37  PavedDrive     1460 non-null   object
 38  PoolQC         7 non-null      object
 39  Fence          281 non-null    object
 40  MiscFeature    54 non-null     object
 41  SaleType       1460 non-null   object
 42  SaleCondition  1460 non-null   object
dtypes: object(43)
memory usage: 490.6+ KB

In [5]:
houses_categorical_cols.columns[houses_categorical_cols.isna().any()]

Index(['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinType2', 'Electrical', 'FireplaceQu',
       'GarageType', 'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC',
       'Fence', 'MiscFeature'],
      dtype='object')

For a lot of these categories a missing value means that feature is not there so we can just fill that category with 'None' or something similar.

List of columns for which missing value means no feature:
`Alley`, `MasVnrType`, `BsmtQual`, `BsmtCond`, `BsmtExposure`,
`BsmtFinType1`, `BsmtFinType2`, `FireplaceQu`, `GarageType`, 
`GarageFinish`, `GarageQual`, `GarageCond`, `PoolQC`,
`Fence`, `MiscFeature`

List of columns for which missing values might mean something else:
`Electrical`,

For all the categories on the first list we will just fill the missing values with 'None'. The remaining category will be dealt with separately.

In [6]:
missing_features_cols = ['Alley', 'MasVnrType', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
'BsmtFinType1', 'BsmtFinType2', 'FireplaceQu', 'GarageType', 
'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC',
'Fence', 'MiscFeature']

for feature in missing_features_cols:
    houses[feature] = houses[feature].fillna('None')

As seen below, there is only one house without Electrical information. I propose that we use either the neighborhood or the year in which it was built/remodeled to choose which category does it belong to.

In [151]:
houses['Electrical'][houses['Electrical'].isna()==True] # This gives only house 1379

mysterious_house = houses.iloc[1379] 

print(mysterious_house['Neighborhood'], mysterious_house['YearBuilt'], mysterious_house['YearRemodAdd'])

Timber 2006 2007

In [152]:
print(houses.groupby('Neighborhood')['Electrical'].get_group('Timber').describe() )
print(houses.groupby('YearBuilt')['Electrical'].get_group(2006).describe())
print(houses.groupby('YearRemodAdd')['Electrical'].get_group(2007).describe())

count        37
unique        2
top       SBrkr
freq         36
Name: Electrical, dtype: object
count        66
unique        1
top       SBrkr
freq         66
Name: Electrical, dtype: object
count        75
unique        1
top       SBrkr
freq         75
Name: Electrical, dtype: object

Seems like the most reasonable choise is to assign 'SBrkr'.

In [153]:
houses['Electrical'] = houses['Electrical'].fillna('SBrkr')

In [154]:
houses_categorical_cols = houses.select_dtypes(exclude='number')
houses_categorical_cols.columns[houses_categorical_cols.isna().any()]

Index([], dtype='object')

Now we are done filling all the missing categorical data.

## Impute Missing Data for Numerical Values

In [7]:
houses_numerical_cols.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 37 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MSSubClass     1460 non-null   int64
 1   LotFrontage    1201 non-null   float64
 2   LotArea        1460 non-null   int64
 3   OverallQual    1460 non-null   int64
 4   OverallCond    1460 non-null   int64
 5   YearBuilt      1460 non-null   int64
 6   YearRemodAdd   1460 non-null   int64
 7   MasVnrArea     1452 non-null   float64
 8   BsmtFinSF1     1460 non-null   int64
 9   BsmtFinSF2     1460 non-null   int64
 10  BsmtUnfSF      1460 non-null   int64
 11  TotalBsmtSF    1460 non-null   int64
 12  1stFlrSF       1460 non-null   int64
 13  2ndFlrSF       1460 non-null   int64
 14  LowQualFinSF   1460 non-null   int64
 15  GrLivArea      1460 non-null   int64
 16  BsmtFullBath   1460 non-null   int64
 17  BsmtHalfBath   1460 non-null   int64
 18  FullBath       1460 non-null   int64
 19  HalfBath       1460 non-null   int64
 20  BedroomAbvGr   1460 non-null   int64
 21  KitchenAbvGr   1460 non-null   int64
 22  TotRmsAbvGrd   1460 non-null   int64
 23  Fireplaces     1460 non-null   int64
 24  GarageYrBlt    1379 non-null   float64
 25  GarageCars     1460 non-null   int64
 26  GarageArea     1460 non-null   int64
 27  WoodDeckSF     1460 non-null   int64
 28  OpenPorchSF    1460 non-null   int64
 29  EnclosedPorch  1460 non-null   int64
 30  3SsnPorch      1460 non-null   int64
 31  ScreenPorch    1460 non-null   int64
 32  PoolArea       1460 non-null   int64
 33  MiscVal        1460 non-null   int64
 34  MoSold         1460 non-null   int64
 35  YrSold         1460 non-null   int64
 36  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(34)
memory usage: 422.2 KB

Question: How do we deal with the different missing nummerical values? 

LotFrontage shows the length of the adjacent street, maybe we should use the average/median(?)

MasVnrArea shows the area of the masonry work, here a missing value indicates zero area so we fill it out with zeros

GarageYrBlt shows the year in which the garage was built, here a missing value indicates no garage but I don't know if putting year 0 is too much of a penalty. The value here should somehow make a house with a garage more expensive than a house without one. Ideas?

Update: I learned there is a thing called sklearn.imputer. Maybe we can check there for options.
Update 2: I think we should use the k nearest neighbors imputer from sklearn. The question is which neighbors to consider, or which columns. https://scikit-learn.org/stable/auto_examples/impute/plot_missing_values.html#sphx-glr-auto-examples-impute-plot-missing-values-py

We can use LotArea, LotConfig, 1stFlrSF to regress on

In [9]:
houses['MasVnrArea'] = houses['MasVnrArea'].fillna(0)

In [10]:
houses['LotFrontage'].describe()

count    1201.000000
mean       70.049958
std        24.284752
min        21.000000
25%        59.000000
50%        69.000000
75%        80.000000
max       313.000000
Name: LotFrontage, dtype: float64

In [11]:
#This failed at first because 'LotConfig' is categorical, maybe we should've dealt with those first.
#I added some cells above to deal with categorical data first.
#Now let's try to encode the categorical data into numerical labels to able to do regression.

from sklearn.preprocessing import LabelEncoder

labelencoder = LabelEncoder()

houses['LotConfig_labels'] = labelencoder.fit_transform(houses['LotConfig'])


from sklearn.impute import KNNImputer

imputer = KNNImputer()
houses[['LotFrontage','LotArea', 'LotConfig_labels', '1stFlrSF']] = imputer.fit_transform(houses[['LotFrontage','LotArea', 'LotConfig_labels', '1stFlrSF']])

In [12]:
houses['LotFrontage'].describe()

count    1460.000000
mean       71.100000
std        23.855761
min        21.000000
25%        60.000000
50%        70.000000
75%        82.000000
max       313.000000
Name: LotFrontage, dtype: float64

The regression seems to have worked since it didnt change quantitites by too much.

Now there's only one more variable to clean: GarageYrBlt

In [13]:
houses[houses['GarageYrBlt'].isna()]

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotConfig_labels
39,90,RL,65.0,6040.0,Pave,None,Reg,Lvl,AllPub,Inside,...,None,None,None,0,6,2008,WD,AdjLand,82000,4.0
48,190,RM,33.0,4456.0,Pave,None,Reg,Lvl,AllPub,Inside,...,None,None,None,0,6,2009,New,Partial,113000,4.0
78,90,RL,72.0,10778.0,Pave,None,Reg,Lvl,AllPub,Inside,...,None,None,None,0,4,2010,WD,Normal,136500,4.0
88,50,C (all),105.0,8470.0,Pave,None,IR1,Lvl,AllPub,Corner,...,None,MnPrv,None,0,10,2009,ConLD,Abnorml,85000,0.0
89,20,RL,60.0,8070.0,Pave,None,Reg,Lvl,AllPub,Inside,...,None,None,None,0,8,2007,WD,Normal,123600,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1349,70,RM,50.0,5250.0,Pave,Pave,Reg,Lvl,AllPub,Inside,...,None,None,None,0,12,2008,WD,Normal,122000,4.0
1407,20,RL,66.0,8780.0,Pave,None,IR1,Lvl,AllPub,Corner,...,None,MnPrv,None,0,3,2009,WD,Normal,112000,0.0
1449,180,RM,21.0,1533.0,Pave,None,Reg,Lvl,AllPub,Inside,...,None,None,None,0,8,2006,WD,Abnorml,92000,4.0
1450,90,RL,60.0,9000.0,Pave,None,Reg,Lvl,AllPub,FR2,...,None,None,None,0,9,2009,WD,Normal,136000,2.0
1453,20,RL,90.0,17217.0,Pave,None,Reg,Lvl,AllPub,Inside,...,None,None,None,0,7,2006,WD,Abnorml,84500,4.0

In [14]:
houses[houses['GarageYrBlt'].isna()].groupby('LotConfig').describe()

          MSSubClass                                                       \
               count       mean        std   min   25%   50%   75%    max
LotConfig
Corner          13.0  46.538462  25.115120  20.0  30.0  50.0  50.0   90.0
CulDSac          1.0  90.000000        NaN  90.0  90.0  90.0  90.0   90.0
FR2              3.0  53.333333  35.118846  20.0  35.0  50.0  70.0   90.0
Inside          64.0  77.500000  63.044454  20.0  30.0  50.0  90.0  190.0

          LotFrontage             ... SalePrice           LotConfig_labels  \
                count       mean  ...       75%       max            count
LotConfig                         ...
Corner           13.0  81.292308  ...  112000.0  141000.0             13.0
CulDSac           1.0  35.000000  ...  127500.0  127500.0              1.0
FR2               3.0  62.666667  ...  125500.0  136000.0              3.0
Inside           64.0  57.150000  ...  124750.0  200500.0             64.0


          mean  std  min  25%  50%  75%  max
LotConfig
Corner     0.0  0.0  0.0  0.0  0.0  0.0  0.0
CulDSac    1.0  NaN  1.0  1.0  1.0  1.0  1.0
FR2        2.0  0.0  2.0  2.0  2.0  2.0  2.0
Inside     4.0  0.0  4.0  4.0  4.0  4.0  4.0

[4 rows x 304 columns]

In [15]:
houses[houses['BldgType']=='1Fam'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 1220 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MSSubClass        1220 non-null   int64
 1   MSZoning          1220 non-null   object
 2   LotFrontage       1220 non-null   float64
 3   LotArea           1220 non-null   float64
 4   Street            1220 non-null   object
 5   Alley             1220 non-null   object
 6   LotShape          1220 non-null   object
 7   LandContour       1220 non-null   object
 8   Utilities         1220 non-null   object
 9   LotConfig         1220 non-null   object
 10  LandSlope         1220 non-null   object
 11  Neighborhood      1220 non-null   object
 12  Condition1        1220 non-null   object
 13  Condition2        1220 non-null   object
 14  BldgType          1220 non-null   object
 15  HouseStyle        1220 non-null   object
 16  OverallQual       1220 non-null   int64
 17  OverallCond       1220 non-null   int64
 18  YearBuilt         1220 non-null   int64
 19  YearRemodAdd      1220 non-null   int64
 20  RoofStyle         1220 non-null   object
 21  RoofMatl          1220 non-null   object
 22  Exterior1st       1220 non-null   object
 23  Exterior2nd       1220 non-null   object
 24  MasVnrType        1220 non-null   object
 25  MasVnrArea        1220 non-null   float64
 26  ExterQual         1220 non-null   object
 27  ExterCond         1220 non-null   object
 28  Foundation        1220 non-null   object
 29  BsmtQual          1220 non-null   object
 30  BsmtCond          1220 non-null   object
 31  BsmtExposure      1220 non-null   object
 32  BsmtFinType1      1220 non-null   object
 33  BsmtFinSF1        1220 non-null   int64
 34  BsmtFinType2      1220 non-null   object
 35  BsmtFinSF2        1220 non-null   int64
 36  BsmtUnfSF         1220 non-null   int64
 37  TotalBsmtSF       1220 non-null   int64
 38  Heating           1220 non-null   object
 39  HeatingQC         1220 non-null   object
 40  CentralAir        1220 non-null   object
 41  Electrical        1219 non-null   object
 42  1stFlrSF          1220 non-null   float64
 43  2ndFlrSF          1220 non-null   int64
 44  LowQualFinSF      1220 non-null   int64
 45  GrLivArea         1220 non-null   int64
 46  BsmtFullBath      1220 non-null   int64
 47  BsmtHalfBath      1220 non-null   int64
 48  FullBath          1220 non-null   int64
 49  HalfBath          1220 non-null   int64
 50  BedroomAbvGr      1220 non-null   int64
 51  KitchenAbvGr      1220 non-null   int64
 52  KitchenQual       1220 non-null   object
 53  TotRmsAbvGrd      1220 non-null   int64
 54  Functional        1220 non-null   object
 55  Fireplaces        1220 non-null   int64
 56  FireplaceQu       1220 non-null   object
 57  GarageType        1220 non-null   object
 58  GarageYrBlt       1166 non-null   float64
 59  GarageFinish      1220 non-null   object
 60  GarageCars        1220 non-null   int64
 61  GarageArea        1220 non-null   int64
 62  GarageQual        1220 non-null   object
 63  GarageCond        1220 non-null   object
 64  PavedDrive        1220 non-null   object
 65  WoodDeckSF        1220 non-null   int64
 66  OpenPorchSF       1220 non-null   int64
 67  EnclosedPorch     1220 non-null   int64
 68  3SsnPorch         1220 non-null   int64
 69  ScreenPorch       1220 non-null   int64
 70  PoolArea          1220 non-null   int64
 71  PoolQC            1220 non-null   object
 72  Fence             1220 non-null   object
 73  MiscFeature       1220 non-null   object
 74  MiscVal           1220 non-null   int64
 75  MoSold            1220 non-null   int64
 76  YrSold            1220 non-null   int64
 77  SaleType          1220 non-null   object
 78  SaleCondition     1220 non-null   object
 79  SalePrice         1220 non-null   int64
 80  LotConfig_labels  1220 non-null   float64
dtypes: float64(6), int64(32), object(43)
memory usage: 781.6+ KB

In [16]:
houses.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   MSSubClass        1460 non-null   int64
 1   MSZoning          1460 non-null   object
 2   LotFrontage       1460 non-null   float64
 3   LotArea           1460 non-null   float64
 4   Street            1460 non-null   object
 5   Alley             1460 non-null   object
 6   LotShape          1460 non-null   object
 7   LandContour       1460 non-null   object
 8   Utilities         1460 non-null   object
 9   LotConfig         1460 non-null   object
 10  LandSlope         1460 non-null   object
 11  Neighborhood      1460 non-null   object
 12  Condition1        1460 non-null   object
 13  Condition2        1460 non-null   object
 14  BldgType          1460 non-null   object
 15  HouseStyle        1460 non-null   object
 16  OverallQual       1460 non-null   int64
 17  OverallCond       1460 non-null   int64
 18  YearBuilt         1460 non-null   int64
 19  YearRemodAdd      1460 non-null   int64
 20  RoofStyle         1460 non-null   object
 21  RoofMatl          1460 non-null   object
 22  Exterior1st       1460 non-null   object
 23  Exterior2nd       1460 non-null   object
 24  MasVnrType        1460 non-null   object
 25  MasVnrArea        1460 non-null   float64
 26  ExterQual         1460 non-null   object
 27  ExterCond         1460 non-null   object
 28  Foundation        1460 non-null   object
 29  BsmtQual          1460 non-null   object
 30  BsmtCond          1460 non-null   object
 31  BsmtExposure      1460 non-null   object
 32  BsmtFinType1      1460 non-null   object
 33  BsmtFinSF1        1460 non-null   int64
 34  BsmtFinType2      1460 non-null   object
 35  BsmtFinSF2        1460 non-null   int64
 36  BsmtUnfSF         1460 non-null   int64
 37  TotalBsmtSF       1460 non-null   int64
 38  Heating           1460 non-null   object
 39  HeatingQC         1460 non-null   object
 40  CentralAir        1460 non-null   object
 41  Electrical        1459 non-null   object
 42  1stFlrSF          1460 non-null   float64
 43  2ndFlrSF          1460 non-null   int64
 44  LowQualFinSF      1460 non-null   int64
 45  GrLivArea         1460 non-null   int64
 46  BsmtFullBath      1460 non-null   int64
 47  BsmtHalfBath      1460 non-null   int64
 48  FullBath          1460 non-null   int64
 49  HalfBath          1460 non-null   int64
 50  BedroomAbvGr      1460 non-null   int64
 51  KitchenAbvGr      1460 non-null   int64
 52  KitchenQual       1460 non-null   object
 53  TotRmsAbvGrd      1460 non-null   int64
 54  Functional        1460 non-null   object
 55  Fireplaces        1460 non-null   int64
 56  FireplaceQu       1460 non-null   object
 57  GarageType        1460 non-null   object
 58  GarageYrBlt       1379 non-null   float64
 59  GarageFinish      1460 non-null   object
 60  GarageCars        1460 non-null   int64
 61  GarageArea        1460 non-null   int64
 62  GarageQual        1460 non-null   object
 63  GarageCond        1460 non-null   object
 64  PavedDrive        1460 non-null   object
 65  WoodDeckSF        1460 non-null   int64
 66  OpenPorchSF       1460 non-null   int64
 67  EnclosedPorch     1460 non-null   int64
 68  3SsnPorch         1460 non-null   int64
 69  ScreenPorch       1460 non-null   int64
 70  PoolArea          1460 non-null   int64
 71  PoolQC            1460 non-null   object
 72  Fence             1460 non-null   object
 73  MiscFeature       1460 non-null   object
 74  MiscVal           1460 non-null   int64
 75  MoSold            1460 non-null   int64
 76  YrSold            1460 non-null   int64
 77  SaleType          1460 non-null   object
 78  SaleCondition     1460 non-null   object
 79  SalePrice         1460 non-null   int64
 80  LotConfig_labels  1460 non-null   float64
dtypes: float64(6), int64(32), object(43)
memory usage: 924.0+ KB